
package mini.gui;

import java.awt.Color;
import java.awt.Font;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import mini.pojo.UserProfilePojo;

/**
 *
 * @author bikrant bikram
 */
public class BusManagementOptionFrame extends javax.swing.JFrame {

    public BusManagementOptionFrame() {
        initComponents();
       super.setIconImage(new ImageIcon(getClass().getResource("/images/LogoFinal.PNG")).getImage());    
        super.setTitle("MINI");    
        this.setLocationRelativeTo(null);
         lblUserId.setText(UserProfilePojo.getUserId());
        lblUserName.setText(UserProfilePojo.getUserName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblLogout = new javax.swing.JLabel();
        lblUserId = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        jbrEditBus = new javax.swing.JRadioButton();
        jbrShowAllBus = new javax.swing.JRadioButton();
        jbrDriverManagement = new javax.swing.JRadioButton();
        jbrBusArrangement = new javax.swing.JRadioButton();
        btnEnter = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();
        jbrShowBusStatus = new javax.swing.JRadioButton();
        jbrAddBus = new javax.swing.JRadioButton();
        jbrShowBusOnDisplay = new javax.swing.JRadioButton();
        jbrRemoveBusFrame = new javax.swing.JRadioButton();
        jbrAddRout = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\abhishek maurya\\Desktop\\mini images\\BusIcon.PNG")); // NOI18N

        lblLogout.setForeground(new java.awt.Color(0, 51, 102));
        lblLogout.setText("logout");
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLogoutMouseExited(evt);
            }
        });

        lblUserId.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblUserId.setForeground(new java.awt.Color(0, 51, 102));
        lblUserId.setText("userId");

        lblUserName.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblUserName.setForeground(new java.awt.Color(0, 51, 102));
        lblUserName.setText("Username");

        jbrEditBus.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jbrEditBus);
        jbrEditBus.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jbrEditBus.setForeground(new java.awt.Color(0, 51, 102));
        jbrEditBus.setText("Edit Bus");

        jbrShowAllBus.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jbrShowAllBus);
        jbrShowAllBus.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jbrShowAllBus.setForeground(new java.awt.Color(0, 51, 102));
        jbrShowAllBus.setText("Show All Bus");

        jbrDriverManagement.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jbrDriverManagement);
        jbrDriverManagement.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jbrDriverManagement.setForeground(new java.awt.Color(0, 51, 102));
        jbrDriverManagement.setText("Driver Management ");

        jbrBusArrangement.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jbrBusArrangement);
        jbrBusArrangement.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jbrBusArrangement.setForeground(new java.awt.Color(0, 51, 102));
        jbrBusArrangement.setText("Bus Arrangement");

        btnEnter.setBackground(new java.awt.Color(0, 51, 102));
        btnEnter.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnEnter.setForeground(new java.awt.Color(255, 255, 255));
        btnEnter.setText("Enter");
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterActionPerformed(evt);
            }
        });

        btnQuit.setBackground(new java.awt.Color(0, 51, 102));
        btnQuit.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnQuit.setForeground(new java.awt.Color(255, 255, 255));
        btnQuit.setText("Back");
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });

        jbrShowBusStatus.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jbrShowBusStatus);
        jbrShowBusStatus.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jbrShowBusStatus.setForeground(new java.awt.Color(0, 51, 102));
        jbrShowBusStatus.setText("Show bus status");
        jbrShowBusStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbrShowBusStatusActionPerformed(evt);
            }
        });

        jbrAddBus.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jbrAddBus);
        jbrAddBus.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jbrAddBus.setForeground(new java.awt.Color(0, 51, 102));
        jbrAddBus.setText("Add Bus");

        jbrShowBusOnDisplay.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jbrShowBusOnDisplay);
        jbrShowBusOnDisplay.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jbrShowBusOnDisplay.setForeground(new java.awt.Color(0, 51, 102));
        jbrShowBusOnDisplay.setText("Show Bus  On Display");
        jbrShowBusOnDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbrShowBusOnDisplayActionPerformed(evt);
            }
        });

        jbrRemoveBusFrame.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jbrRemoveBusFrame);
        jbrRemoveBusFrame.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jbrRemoveBusFrame.setForeground(new java.awt.Color(0, 51, 102));
        jbrRemoveBusFrame.setText("Remove Bus");

        jbrAddRout.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jbrAddRout);
        jbrAddRout.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jbrAddRout.setForeground(new java.awt.Color(0, 51, 102));
        jbrAddRout.setText("Add Rout");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUserName)
                    .addComponent(lblUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jbrShowBusOnDisplay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 260, Short.MAX_VALUE)
                        .addComponent(lblLogout)
                        .addGap(23, 23, 23))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jbrBusArrangement)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnEnter)
                                .addGap(18, 18, 18)
                                .addComponent(btnQuit))
                            .addComponent(jbrRemoveBusFrame)
                            .addComponent(jbrAddBus)
                            .addComponent(jbrAddRout)
                            .addComponent(jbrShowAllBus)
                            .addComponent(jbrShowBusStatus)
                            .addComponent(jbrEditBus)
                            .addComponent(jbrDriverManagement))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogout)
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jbrShowBusOnDisplay)
                        .addGap(18, 18, 18)
                        .addComponent(jbrAddBus)
                        .addGap(18, 18, 18)
                        .addComponent(jbrAddRout)
                        .addGap(18, 18, 18)
                        .addComponent(jbrShowAllBus)
                        .addGap(18, 18, 18)
                        .addComponent(jbrDriverManagement)
                        .addGap(18, 18, 18)
                        .addComponent(jbrBusArrangement)))
                .addGap(18, 18, 18)
                .addComponent(jbrRemoveBusFrame)
                .addGap(18, 18, 18)
                .addComponent(jbrEditBus)
                .addGap(18, 18, 18)
                .addComponent(jbrShowBusStatus)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnter)
                    .addComponent(btnQuit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblUserId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblUserName)
                .addGap(150, 150, 150))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        // TODO add your handling code here:
        LoginFrame loginFrame= new LoginFrame();
        loginFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblLogoutMouseClicked

    private void lblLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseEntered
        // TODO add your handling code here:

        lblLogout.setForeground(Color.BLUE);
        Font f= new Font("Tohoma",Font.ITALIC,12);
        lblLogout.setFont(f);
    }//GEN-LAST:event_lblLogoutMouseEntered

    private void lblLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseExited
        // TODO add your handling code here:
        Color c= new Color(205,102,0);

        lblLogout.setForeground(c);
        Font f= new Font("Tohoma",Font.PLAIN,12);
        lblLogout.setFont(f);
    }//GEN-LAST:event_lblLogoutMouseExited

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed
       
        if(jbrShowBusOnDisplay.isSelected())
        {
            ShowBusOnDisplayFrame showBusOnDispalyFrame= new ShowBusOnDisplayFrame() ;
            showBusOnDispalyFrame.setVisible(true);
            this.dispose();
             
        }
        else if(jbrAddBus.isSelected())
        {
            AddBusFrame addBusFrame= new AddBusFrame();
            addBusFrame.setVisible(true);
            this.dispose();
        }
        else if(jbrEditBus.isSelected())
        {
            EditBusFrame editBusFrame= new EditBusFrame();
            editBusFrame.setVisible(true);
            this.dispose();
            
        }
        else if(jbrShowAllBus.isSelected())
        {
            ShowAllBusFrame showAllBusFrame= new ShowAllBusFrame() ;
            showAllBusFrame.setVisible(true);
            this.dispose();
        }
        else if(jbrDriverManagement.isSelected())
        {
            DriverManagementOptionFrame driverManagementOptionFrame= new DriverManagementOptionFrame();
            driverManagementOptionFrame.setVisible(true);
            this.dispose();
        }
        else if(jbrBusArrangement.isSelected())
        {
            BusArrangementOptionFrame busArrangementOptionFrame= new BusArrangementOptionFrame();
            busArrangementOptionFrame.setVisible(true);
            this.dispose();
            
        }
        else if(jbrShowBusStatus.isSelected())
        {
            ShowBusStatusFrame showBusStatusFrame= new ShowBusStatusFrame();
            showBusStatusFrame.setVisible(true);
            this.dispose();
            
        }
        else if(jbrRemoveBusFrame.isSelected())
        {
            RemoveBusFrame removeBusFrame= new RemoveBusFrame();
           removeBusFrame.setVisible(true);
           this.dispose();
        }
        else if(jbrAddRout.isSelected())
        {
            AddRoutFrame addRouteFrame= new AddRoutFrame();
            addRouteFrame.setVisible(true);
            this.dispose();
            
        }
        else
            JOptionPane.showMessageDialog(null,"Please make a selection first");
        
        
        
        
        
    }//GEN-LAST:event_btnEnterActionPerformed

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        
        int ans=   JOptionPane.showConfirmDialog(null,"are u sure ","conformation",JOptionPane.INFORMATION_MESSAGE,JOptionPane.YES_NO_OPTION);
        if(ans!=JOptionPane.YES_OPTION)
            return;
        UserOptionFrame userOptionFrame= new UserOptionFrame();
        userOptionFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQuitActionPerformed

    private void jbrShowBusOnDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbrShowBusOnDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbrShowBusOnDisplayActionPerformed

    private void jbrShowBusStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbrShowBusStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbrShowBusStatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BusManagementOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BusManagementOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BusManagementOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BusManagementOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BusManagementOptionFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnter;
    private javax.swing.JButton btnQuit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jbrAddBus;
    private javax.swing.JRadioButton jbrAddRout;
    private javax.swing.JRadioButton jbrBusArrangement;
    private javax.swing.JRadioButton jbrDriverManagement;
    private javax.swing.JRadioButton jbrEditBus;
    private javax.swing.JRadioButton jbrRemoveBusFrame;
    private javax.swing.JRadioButton jbrShowAllBus;
    private javax.swing.JRadioButton jbrShowBusOnDisplay;
    private javax.swing.JRadioButton jbrShowBusStatus;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblUserId;
    private javax.swing.JLabel lblUserName;
    // End of variables declaration//GEN-END:variables
}
