/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mymgmtapp.gui;

import javax.swing.JOptionPane;

/**
 *
 * @author bikrant bikram
 */
public class OptionFrame extends javax.swing.JFrame {

    /**
     * Creates new form OptionFrame
     */
    public OptionFrame() {
        initComponents();
    super.setLocationRelativeTo(null);     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jbrAddEmp = new javax.swing.JRadioButton();
        jbrSearchEmp = new javax.swing.JRadioButton();
        jbrQuit = new javax.swing.JRadioButton();
        jbrShowAllEmp = new javax.swing.JRadioButton();
        btnDoTask = new javax.swing.JButton();
        jbrUpdateEmp = new javax.swing.JRadioButton();
        jbrDeleteEmp = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setForeground(new java.awt.Color(255, 255, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 0));
        jLabel1.setText("select your choice");

        jbrAddEmp.setBackground(new java.awt.Color(0, 102, 102));
        jbrAddEmp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbrAddEmp.setForeground(new java.awt.Color(255, 255, 0));
        jbrAddEmp.setText("add employee");

        jbrSearchEmp.setBackground(new java.awt.Color(0, 102, 102));
        jbrSearchEmp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbrSearchEmp.setForeground(new java.awt.Color(255, 255, 0));
        jbrSearchEmp.setText("search emplayee");

        jbrQuit.setBackground(new java.awt.Color(0, 102, 102));
        jbrQuit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbrQuit.setForeground(new java.awt.Color(255, 255, 0));
        jbrQuit.setText("quit");

        jbrShowAllEmp.setBackground(new java.awt.Color(0, 102, 102));
        jbrShowAllEmp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbrShowAllEmp.setForeground(new java.awt.Color(255, 255, 0));
        jbrShowAllEmp.setText("show all employee");
        jbrShowAllEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbrShowAllEmpActionPerformed(evt);
            }
        });

        btnDoTask.setText("Do task");
        btnDoTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoTaskActionPerformed(evt);
            }
        });

        jbrUpdateEmp.setBackground(new java.awt.Color(0, 102, 102));
        jbrUpdateEmp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbrUpdateEmp.setForeground(new java.awt.Color(255, 255, 0));
        jbrUpdateEmp.setText("Update employee");

        jbrDeleteEmp.setBackground(new java.awt.Color(0, 102, 102));
        jbrDeleteEmp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbrDeleteEmp.setForeground(new java.awt.Color(255, 255, 0));
        jbrDeleteEmp.setText("Delete employee");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 204));
        jLabel2.setText("EMPLOYEE MANAGEMENT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbrUpdateEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbrShowAllEmp)
                    .addComponent(jbrSearchEmp)
                    .addComponent(jbrAddEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jbrDeleteEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbrQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(btnDoTask)
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 82, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(105, 105, 105))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jbrAddEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jbrSearchEmp)
                .addGap(18, 18, 18)
                .addComponent(jbrShowAllEmp)
                .addGap(18, 18, 18)
                .addComponent(jbrDeleteEmp)
                .addGap(8, 8, 8)
                .addComponent(jbrUpdateEmp)
                .addGap(14, 14, 14)
                .addComponent(jbrQuit)
                .addGap(18, 18, 18)
                .addComponent(btnDoTask)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbrShowAllEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbrShowAllEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbrShowAllEmpActionPerformed

    private void btnDoTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoTaskActionPerformed

        if(jbrAddEmp.isSelected())
        {
           AddEmployeeFrame addEmployeeFrame=new AddEmployeeFrame () ;
           addEmployeeFrame.setVisible(true);
           this.dispose();
        }
        
        else if (jbrSearchEmp.isSelected())
        {
          SearchEmployeeFrame searchEmployeeFrame = new SearchEmployeeFrame()  ;
          searchEmployeeFrame.setVisible(true);
            this.dispose();
        }
        else if(jbrShowAllEmp.isSelected())
        {
            ViewAllEmployeeFrame viewAllEmployeeFrame = new ViewAllEmployeeFrame()  ;
          viewAllEmployeeFrame.setVisible(true);
              this.dispose();
        }
        else if(jbrDeleteEmp.isSelected())
        {
            DeleteEmployeeFrame deleteEmployeeFrame = new DeleteEmployeeFrame()  ;
          deleteEmployeeFrame.setVisible(true);
              this.dispose();
        }
        else if(jbrUpdateEmp.isSelected())
        {
            UpdateEmployeeFrame updateEmployeeFrame = new UpdateEmployeeFrame()  ;
          updateEmployeeFrame.setVisible(true);
              this.dispose();
        }
        
        else if(jbrQuit.isSelected())
        {
             // int ans=  JOptionPane.showMessageDialog(null, "are u sure","conformation",JOptionPane.YES_NO_OPTION);
               //     JOptionPane.showMessageDialog(null, "thanku");
                  
                   int answer=JOptionPane.showConfirmDialog(null, "are u sure", "quitting?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                    if( answer==JOptionPane.YES_OPTION)
                    {
                        
                        System.exit(0);
                    }
                    

        }
        else
        {
            JOptionPane.showMessageDialog(null, "choose any option");
        }
        
        
        
    }//GEN-LAST:event_btnDoTaskActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OptionFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoTask;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jbrAddEmp;
    private javax.swing.JRadioButton jbrDeleteEmp;
    private javax.swing.JRadioButton jbrQuit;
    private javax.swing.JRadioButton jbrSearchEmp;
    private javax.swing.JRadioButton jbrShowAllEmp;
    private javax.swing.JRadioButton jbrUpdateEmp;
    // End of variables declaration//GEN-END:variables
}
