/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package onlinequizeapp.gui;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import onlinequizeapp.dao.PerformanceDAO;
import onlinequizeapp.dao.QuestionDAO;
import onlinequizeapp.pojo.ExamPojo;
import onlinequizeapp.pojo.PerformancePojo;
import onlinequizeapp.pojo.QuestionPojo;
import onlinequizeapp.pojo.QuestionStore;
import onlinequizeapp.pojo.UserProfile;

/**
 *
 * @author bikrant bikram
 */
public class TakeTestFrame extends javax.swing.JFrame {

    /**
     * Creates new form TakeTestFrame
     */
  
     private ExamPojo newExam;
    private QuestionStore qstore;
   // private AnswerStorePojo astore;
    private int pos,qno=0;
    
    private HashMap<Integer,String> hm= new HashMap<>();
  
    public TakeTestFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        lblUserName.setText("welcome "+UserProfile.getUserName());
         
     //   astore= new AnswerStorePojo();
       
        
         
    }
    public TakeTestFrame(ExamPojo newExam)
    {
        this();
        
     this.newExam= newExam;   
     try {
             qstore = QuestionDAO.getQuestions(newExam);
         } catch (SQLException ex) {
             ex.printStackTrace();

         }
     
        set();
        lblQno.setText(lblQno.getText()+ (qno+1));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt = new javax.swing.JTextArea();
        jbrOption1 = new javax.swing.JRadioButton();
        jbrOption2 = new javax.swing.JRadioButton();
        jbrOption4 = new javax.swing.JRadioButton();
        jbrOption3 = new javax.swing.JRadioButton();
        btnPrevious = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnDone = new javax.swing.JButton();
        lblUserName = new javax.swing.JLabel();
        lblQno = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt.setColumns(20);
        txt.setRows(5);
        jScrollPane1.setViewportView(txt);

        buttonGroup1.add(jbrOption1);
        jbrOption1.setText("jRadioButton1");

        buttonGroup1.add(jbrOption2);
        jbrOption2.setText("jRadioButton2");

        buttonGroup1.add(jbrOption4);
        jbrOption4.setText("jRadioButton3");

        buttonGroup1.add(jbrOption3);
        jbrOption3.setText("jRadioButton4");

        btnPrevious.setText("previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        btnNext.setText("next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnCancel.setText("cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnDone.setText("done");
        btnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneActionPerformed(evt);
            }
        });

        lblUserName.setText("jLabel1");

        lblQno.setText("jLabel1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblQno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jbrOption3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbrOption4))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jbrOption1)
                                    .addGap(110, 110, 110)
                                    .addComponent(jbrOption2)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnPrevious)
                        .addGap(18, 18, 18)
                        .addComponent(btnNext)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDone))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblUserName)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUserName)
                .addGap(76, 76, 76)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQno))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbrOption1)
                    .addComponent(jbrOption2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbrOption4)
                    .addComponent(jbrOption3))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrevious)
                    .addComponent(btnNext)
                    .addComponent(btnCancel)
                    .addComponent(btnDone))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
       
     int a= JOptionPane.showConfirmDialog(null,"are you sure to cancel the paper\n all your answered will be erased  ?", "conformation",JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE);
   if(a==JOptionPane.OK_OPTION)
   {
      StudentOptionsFrame  adminOptionFrame=new  StudentOptionsFrame();
        adminOptionFrame.setVisible(true);
        this.dispose();   
   }
        
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneActionPerformed
int unA=0;
int right=0;
int ans=   JOptionPane.showConfirmDialog(null,"are u sure to submit \n no changes will allow after submission ","conformation",JOptionPane.INFORMATION_MESSAGE,JOptionPane.YES_NO_OPTION);
        if(ans!=JOptionPane.YES_OPTION)
            return;
        ArrayList <QuestionPojo> al = qstore.getAllQuestion();
        for(QuestionPojo o: al)
        {
            String temp= hm.get(o.getQno()-1);
          if(temp==null)
              unA++;
          else if(temp.equalsIgnoreCase(o.getCorrectAnswer())==true)
              right++;  
            
        }
      PerformancePojo pp= new PerformancePojo(newExam.getExamId(),newExam.getLanguage(),UserProfile.getUserName(),right,newExam.getTotalQuestions()-right-unA,unA,(double)(right/newExam.getTotalQuestions())*100); 
         try {
             //    public PerformancePojo(String examId, String language, String userId, int right, int wrong, int unattampted, double per) {
             PerformanceDAO.addPerformance(pp);
              JOptionPane.showMessageDialog(null,"SuccessFully submitted","Submitted",JOptionPane.INFORMATION_MESSAGE);
              StudentOptionsFrame studentOptionsFrame= new StudentOptionsFrame();
              studentOptionsFrame.setVisible(true);
              this.dispose();
             
         } 
         catch (SQLException ex) {
             
     ex.printStackTrace();
     JOptionPane.showMessageDialog(null,"Couldnt submitted","Error!",JOptionPane.ERROR_MESSAGE);
         } 
        
        
    }//GEN-LAST:event_btnDoneActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
     
         getResponce();
         if(qno+1>=newExam.getTotalQuestions())
        {
            
            btnDone.setEnabled(true);
            btnPrevious.setEnabled(true);
            btnNext.setEnabled(false);
            
            JOptionPane.showMessageDialog(null,"no qstn left\n pls click on btn done to store into database","finish", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
           qno++;
       
         set()  ;   
                btnPrevious.setEnabled(true);
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
          getResponce();
           if(qno<=0)
        {
            
            btnPrevious.setEnabled(false);
           //enableAll();
            
            
            JOptionPane.showMessageDialog(null,"no qstn left\n pls click on btn done to store into database","finish", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
         
           
           qno--;
           System.out.println(" for question no"+ qno + " set chalaa");
           
            set();
            btnNext.setEnabled(true);
     
      
        
    }//GEN-LAST:event_btnPreviousActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TakeTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TakeTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TakeTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TakeTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TakeTestFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDone;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton jbrOption1;
    private javax.swing.JRadioButton jbrOption2;
    private javax.swing.JRadioButton jbrOption3;
    private javax.swing.JRadioButton jbrOption4;
    private javax.swing.JLabel lblQno;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JTextArea txt;
    // End of variables declaration//GEN-END:variables
private void set()
{
    QuestionPojo q=qstore.getQusestion(qno);
    //        System.out.println(q);
    txt.setText(q.getQuestion());
    jbrOption1.setText(q.getOption1());
    jbrOption2.setText(q.getOption2());
    jbrOption3.setText(q.getOption3());
    jbrOption4.setText(q.getOption4());
    
    
   // jcCorrectOption.setSelectedItem((Object)q.getCorrectAnswer());
    lblQno.setText("Question no :"+ (qno+1)); 
if(isSelected()!=null)
         {
             switch (isSelected())
             {
                 case "Answer1":
                     jbrOption1.setSelected(true);
                     break;
                  case "Answer2":
                     jbrOption2.setSelected(true);
                     break;
                      case "Answer3":
                     jbrOption3.setSelected(true);
                     break;
                      case "Answer4":
                     jbrOption4.setSelected(true);
                     break;
          
             }
             return;
         }
buttonGroup1.clearSelection();
}

private String isSelected()
{
   return  hm.get(qno);
    
}
private void  getResponce()
{
    
    String temp= (jbrOption1.isSelected()==true)?"Answer1":(jbrOption2.isSelected()==true)?"Answer2":(jbrOption3.isSelected()==true)?"Answer3":(jbrOption4.isSelected()==true)?"Answer4":null;
          hm.put(qno, temp);
             System.out.println(temp+ "      for question no "+ qno); 
    
}
}
